# Generated by Django 2.2.4 on 2019-11-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_current_package_user_last_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_package_user',
            name='package_selected',
        ),
        migrations.RemoveField(
            model_name='current_package_user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='init_schedule',
            name='username',
        ),
        migrations.RemoveField(
            model_name='queue_statistics',
            name='selected_account',
        ),
        migrations.RemoveField(
            model_name='queue_statistics',
            name='username',
        ),
        migrations.RemoveField(
            model_name='scheduler_model',
            name='init_schedule_fk',
        ),
        migrations.RemoveField(
            model_name='scheduler_model',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='scheduler_model',
            name='username',
        ),
        migrations.DeleteModel(
            name='temp_data',
        ),
        migrations.RemoveField(
            model_name='upcomming_queue',
            name='init_schedule_fk',
        ),
        migrations.RemoveField(
            model_name='upcomming_queue',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='upcomming_queue',
            name='schedule_dirtybit',
        ),
        migrations.RemoveField(
            model_name='upcomming_queue',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_transaction',
            name='username',
        ),
        migrations.DeleteModel(
            name='available_package',
        ),
        migrations.DeleteModel(
            name='current_package_user',
        ),
        migrations.DeleteModel(
            name='init_schedule',
        ),
        migrations.DeleteModel(
            name='queue_statistics',
        ),
        migrations.DeleteModel(
            name='scheduler_model',
        ),
        migrations.DeleteModel(
            name='upcomming_queue',
        ),
        migrations.DeleteModel(
            name='user_transaction',
        ),
    ]
