# Generated by Django 2.2.4 on 2019-11-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20191125_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_connection_data',
            name='max_connections',
        ),
        migrations.RemoveField(
            model_name='user_connection_data',
            name='max_seleceted_connections',
        ),
        migrations.RemoveField(
            model_name='user_connection_data',
            name='max_team_members',
        ),
        migrations.RemoveField(
            model_name='user_connection_data',
            name='total_team_members',
        ),
        migrations.AddField(
            model_name='selected_connections',
            name='auto_sync',
            field=models.BooleanField(default=False),
        ),
    ]
