# Generated by Django 2.2.4 on 2019-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20191126_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_connections',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
