# Generated by Django 2.2.4 on 2019-11-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_selected_connections_last_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('bio', models.CharField(blank=True, max_length=5000, null=True)),
                ('business_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('business_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('fan_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('featured_video_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('artists_we_like', models.CharField(blank=True, max_length=1000, null=True)),
                ('connected_instagram_account', models.CharField(blank=True, max_length=1000, null=True)),
                ('cover_source', models.URLField(blank=True, max_length=2000, null=True)),
                ('country_page_likes', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('engagement', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('impressum', models.CharField(blank=True, max_length=1000, null=True)),
                ('new_like_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('overall_star_rating', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('rating_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('talking_about_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('unread_message_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('unread_notif_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('unseen_message_count', models.BigIntegerField(blank=True, max_length=1000, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('were_here_count', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.selected_connections')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
