# Generated by Django 2.2.4 on 2019-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_facebook_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_data',
            name='country_page_likes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='engagement',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='new_like_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='overall_star_rating',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='rating_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='talking_about_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='unread_message_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='unread_notif_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_data',
            name='unseen_message_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
