# Generated by Django 2.2.4 on 2019-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20191126_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_data',
            name='fan_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
