# Generated by Django 2.2.4 on 2019-11-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_auto_20191126_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_data',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
