# Generated by Django 2.2.4 on 2019-11-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_twitter_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('fan_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('views', models.BigIntegerField(blank=True, default=0, null=True)),
                ('videos_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('hit', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.selected_connections')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
