# Generated by Django 2.2.4 on 2019-11-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_youtube_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_data',
            old_name='twitter_id',
            new_name='youtube_id',
        ),
    ]
