# Generated by Django 2.2.4 on 2019-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='read_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
