# Generated by Django 2.2.4 on 2019-11-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_auto_20191128_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification_pannel',
        ),
    ]
