# Generated by Django 2.2.4 on 2019-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_connection_data',
            name='fan_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
